package lexer;


// token类别
public enum TokenType {
    IDENFR, INTCON, STRCON, CHRCON, // 变量命名
    // 关键字和符号
    MAINTK, CONSTTK, INTTK, CHARTK, BREAKTK, CONTINUETK, IFTK,
    ELSETK, NOT, AND, OR, FORTK, GETINTTK, GETCHARTK, PRINTFTK,
    RETURNTK, PLUS, MINU, VOIDTK, MULT, DIV, MOD, LSS, LEQ,
    GRE, GEQ, EQL, NEQ, ASSIGN, SEMICN, COMMA, LPARENT, RPARENT, LBRACK,
    RBRACK, LBRACE, RBRACE
}